services:
  backend:
    build: ./backend
    container_name: doc-agent
    ports:
      - "8081:8081"
    env_file:
      - ./backend/app/.env
    depends_on:
      redis:
        condition: service_healthy
    environment:
      REDIS_URL: redis://redis:6379/0
    volumes:
      - ./serviceAccountKey.json:/app/app/serviceAccountKey.json:ro
       
    

  redis:
    image: redis:7-alpine
    container_name: redis-agent
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - redis_data:/data

volumes:
  redis_data:
